version: '3.3'

services:
  db:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  web:
    build: .
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - static_volume:/static
    ports:
      - "8000:8000"

  nginx:
    image: nginx:latest
    restart: always
    depends_on:
      - web
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_volume:/static
    ports:
      - "80:80"

volumes:
  postgres_data:
  static_volume:
